to resolve IP address of vagrant node from Vagrantfile

diff --git a/bin/create_new_box b/bin/create_new_box
--- a/bin/create_new_box
+++ b/bin/create_new_box
@@ -1,11 +1,26 @@
 #!/bin/bash
 
-NODE=vagrant@192.168.33.10
-BASE_DIR=`dirname $0`/..
-SYNC_CMD=$BASE_DIR/bin/sync_repo
-CHEF_REPO_DIR=$BASE_DIR//chef-solo
 TEMP_PROXY_SH_FIE=/tmp/vagrant-proxy.sh
 TEMP_PROXY_SUDOERS_FIE=/tmp/vagrant-sudoers
+
+#
+# Resolve dirs
+#
+BASE_DIR=$PWD
+if [ ! -f $BASE_DIR/Vagrantfile ]; then
+    echo "ERROR: `basename $0` is a required file/directory" >&2
+    echo "FATAL: This command must be run inside a vagrant root directory." >&2
+    exit 1
+fi
+SYNC_CMD=$BASE_DIR/bin/sync_repo
+CHEF_REPO_DIR=$BASE_DIR/chef-solo
+
+#
+# Host / Node
+#
+HOST=`cat $BASE_DIR/Vagrantfile | grep -vE '^ *#' | grep :hostonly | awk '{ print $3 }' | sed -e 's/"//g'`
+NODE=vagrant@$HOST
+echo "Creating new box with IP-address: $HOST"
 
 #
 # Sync
diff --git a/bin/sync_repo b/bin/sync_repo
--- a/bin/sync_repo
+++ b/bin/sync_repo
@@ -1,7 +1,18 @@
 #!/bin/bash
 
 SHARED_REPO_DIR=~/Developer/workspace/chef-repo
-CHEF_SOLO_DIR=`dirname $0`/../chef-solo
+
+#
+# Resolve base dir
+#
+BASE_DIR=$PWD
+if [ ! -f $BASE_DIR/Vagrantfile ]; then
+    echo "ERROR: `basename $0` is a required file/directory" >&2
+    echo "FATAL: This command must be run inside a vagrant root directory." >&2
+    exit 1
+fi
+SYNC_CMD=$BASE_DIR/bin/sync_repo
+CHEF_SOLO_DIR=$BASE_DIR/chef-solo
 
 #
 # sync
diff --git a/bin/update_box b/bin/update_box
--- a/bin/update_box
+++ b/bin/update_box
@@ -1,9 +1,23 @@
 #!/bin/bash
 
-NODE=vagrant@192.168.33.10
-BASE_DIR=`dirname $0`/..
+#
+# Resolve base dir
+#
+BASE_DIR=$PWD
+if [ ! -f $BASE_DIR/Vagrantfile ]; then
+    echo "ERROR: `basename $0` is a required file/directory" >&2
+    echo "FATAL: This command must be run inside a vagrant root directory." >&2
+    exit 1
+fi
 SYNC_CMD=$BASE_DIR/bin/sync_repo
-CHEF_REPO_DIR=$BASE_DIR/chef-solo
+CHEF_SOLO_DIR=$BASE_DIR/chef-solo
+
+#
+# Host / Node
+#
+HOST=`cat $BASE_DIR/Vagrantfile | grep -vE '^ *#' | grep :hostonly | awk '{ print $3 }' | sed -e 's/"//g'`
+NODE=vagrant@$HOST
+echo "Updating a box of IP-address: $HOST"
 
 #
 # Sync
@@ -18,6 +32,6 @@ vagrant up
 #
 # Chef (chef-solo / knife-solo)
 #
-cd $CHEF_REPO_DIR
+cd $CHEF_SOLO_DIR
 knife solo cook $NODE
 
